#!/bin/tcsh
alias sa source $HOME/etc/_alias
alias va vi $HOME/etc/_alias
alias cell cd $HOME/CELLTOWER
alias sto cd $HOME/stories
alias let cd $HOME/letters
alias etc cd $HOME/etc
alias push 'git push'
alias pu   'git push'
alias pull 'git pull'
alias com  'git commit -m "\!:*"'
