#!/bin/tcsh
alias sa source $HOME/etc/_alias
alias va vi $HOME/etc/_alias
alias cell cd $HOME/CELLTOWER
alias nach cd $HOME/nachos
alias fall cd $HOME/fallacy
alias tv   cd $HOME/tv
alias mp3  cd $HOME/mp3
alias aa   cd $HOME/aahigh
alias snap cd $HOME/SNAPSHOTS
alias sto cd $HOME/stories
alias let cd $HOME/letters
alias etc cd $HOME/etc
alias l   'ls'
alias ll  'ls -l '
alias .   'cd ..'
alias ..  'cd ..'
alias -   'cd -'

# aliases to make using git on my iPhone easier
alias hard  'git reset --hard HEAD'
alias clean 'git clean -nd'
alias cleaf 'git clean -fd'
alias st    'git status'
alias push  'git push'
alias pu    'git push'
alias pull  'git pull'
alias ga    'git add'
#
# alias, "com" ... format to use:
### root:~# com this is a commit message no quotes
# this is to make it easier to commit with
#  messages when using a cellphone with no kybd
alias com  'git commit -m "iSH \!:*" ; git push'
