#!/bin/tcsh
if( -f $HOME/etc/_alias ) then
    source $HOME/etc/_alias
endif

if( -f $HOME/etc/_complete ) then
    source $HOME/etc/_complete
endif


set prompt="%{\033[1;33;44m%}%~%{\033[0;37m%}%# "
