#!/bin/tcsh
# this will only install dotfiles if you do not already have them,
# and if you do, then it will simply tell you that it won't
# overwrite what you have there....
#
if( ! -f $HOME/.profile ) then
    cp -f _bashrc $HOME/.profile
else
    echo "already have a .profile in your home directory!"
endif

if( ! -f $HOME/.tcshrc ) then
    cp -f _tcshrc $HOME/.tcshrc
else
    echo "already have a .tcshrc in your home directory!"
endif
